<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>as</string>
	</array>
	<key>name</key>
	<string>Actionscript 3</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#package</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mxml</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#regexp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable_declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#primitive_types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dynamic_type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#language_constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#language_variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#guess_type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#guess_constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other_operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#arithmetic_operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logical_operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#array_access_operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#vector_creation_operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#use_namespace</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arithmetic_operators</key>
		<dict>
			<key>match</key>
			<string>(\+|\-|/|%|(?&lt;!:)\*)</string>
			<key>name</key>
			<string>keyword.operator.actionscript.3</string>
		</dict>
		<key>array_access_operators</key>
		<dict>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>keyword.operator.actionscript.3</string>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>(?x) (^|\s+|;) (\b(dynamic|final)\b\s+)? (\b(internal|public)\b\s+)? (\b(dynamic|final)\b\s+)? (?=\bclass\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.class.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dynamic_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#use_namespace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arithmetic_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array_access_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#vector_creation_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object_literal</string>
				</dict>
			</array>
		</dict>
		<key>class_declaration</key>
		<dict>
			<key>begin</key>
			<string>(?x) \b(class)\b \s+ ([\.\w]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.actionscript.3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\{</string>
			<key>name</key>
			<string>meta.class_declaration.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#extends</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#implements</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>code_block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.code_block.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dynamic_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arithmetic_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logical_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array_access_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#vector_creation_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#use_namespace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*\*(?!/)</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>@(copy|default|eventType|example|exampleText|includeExample|inheritDoc|internal|param|private|return|see|since|throws)\b</string>
							<key>name</key>
							<string>keyword.other.documentation.actionscript.3.asdoc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.actionscript.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*</string>
					<key>name</key>
					<string>comment.line.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>control_keywords</key>
		<dict>
			<key>match</key>
			<string>\b(if|else|do|while|for|each|continue|return|switch|case|default|break|try|catch|finally|throw|trace)\b</string>
			<key>name</key>
			<string>keyword.control.actionscript.3</string>
		</dict>
		<key>dynamic_type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.actionscript.3</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=:)\s*(\*)</string>
		</dict>
		<key>escapes</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
			<key>name</key>
			<string>constant.character.escape.actionscript.3</string>
		</dict>
		<key>extends</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.actionscript.3</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.actionscript.3</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) \b(extends)\b \s+ ([\.\w]+) \s* (?:, \s* ([\.\w]+))* \s*</string>
			<key>name</key>
			<string>meta.extends.actionscript.3</string>
		</dict>
		<key>function_arguments</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function_arguments.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dynamic_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_type</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>begin</key>
			<string>(?x) \b(function)\b (?:\s+\b(get|set)\b\s+)? \s* ([a-zA-Z0-9_\$]+\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.actionscript.3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>($|;|(?=\{))</string>
			<key>name</key>
			<string>meta.function.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#return_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>guess_constant</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.actionscript.3</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Following convention, let's guess that anything in all caps/digits (possible underscores) is a constant.</string>
			<key>match</key>
			<string>\b([A-Z0-9_]+)\b</string>
		</dict>
		<key>guess_type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.actionscript.3</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Following convention, let's guess that any word starting with one or more capital letters (that contains at least some lower-case letters so that constants aren't detected) refers to a class/type. May be fully-qualified.</string>
			<key>match</key>
			<string>\b((?:[A-Za-z0-9_\$]+\.)*[A-Z]+[a-z]+[A-Za-z0-9_\$]*)\b</string>
		</dict>
		<key>implements</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.actionscript.3</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.actionscript.3</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) \b(implements)\b \s+ ([\.\w]+) \s* (?:, \s* ([\.\w]+))* \s*</string>
			<key>name</key>
			<string>meta.implements.actionscript.3</string>
		</dict>
		<key>import</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.actionscript.3</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.actionscript.3</string>
				</dict>
			</dict>
			<key>match</key>
			<!-- just look for a string of characters and dots so that it doesn't 
				turn off the syntax when the line ends with a dot -->
			<string>(?x) (^|\s+|;) \b(import)\b \s+ ([A-Za-z0-9\$_\.]+(?:\.\*)?) \s* (?=;|$)</string>
			<key>name</key>
			<string>meta.import.actionscript.3</string>
		</dict>
		<key>interface</key>
		<dict>
			<key>begin</key>
			<string>(?x) (^|\s+|;) (\b(internal|public)\b\s+)? (?=\binterface\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.interface.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interface_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>interface_declaration</key>
		<dict>
			<key>begin</key>
			<string>(?x) \b(interface)\b \s+ ([\.\w]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.interface.actionscript.3</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\{</string>
			<key>name</key>
			<string>meta.class_declaration.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#extends</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>language_constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|Infinity|-Infinity|NaN|undefined)\b</string>
			<key>name</key>
			<string>constant.language.actionscript.3</string>
		</dict>
		<key>language_variables</key>
		<dict>
			<key>match</key>
			<string>\b(super|this)\b</string>
			<key>name</key>
			<string>variable.language.actionscript.3</string>
		</dict>
		<key>logical_operators</key>
		<dict>
			<key>match</key>
			<string>(&amp;|&lt;|~|\||&gt;|\^|!|\?)</string>
			<key>name</key>
			<string>keyword.operator.actionscript.3</string>
		</dict>
		<key>metadata_info</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.actionscript.3</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)\s*=</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>begin</key>
			<string>(?x) (^|\s+) ((\w+)\s+)? ((\w+)\s+)? ((\w+)\s+)? (\w+) (?=\s+\bfunction\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=(;|\}))</string>
			<key>name</key>
			<string>meta.method.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code_block</string>
				</dict>
			</array>
		</dict>
		<key>mxml</key>
		<dict>
			<key>begin</key>
			<string>&lt;!\[CDATA\[</string>
			<key>end</key>
			<string>\]\]&gt;</string>
			<key>name</key>
			<string>meta.cdata.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#use_namespace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dynamic_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arithmetic_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array_access_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#vector_creation_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_declaration</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.actionscript.3</string>
		</dict>
		<key>object_literal</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.object_literal.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dynamic_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#guess_constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array_access_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#vector_creation_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
			</array>
		</dict>
		<key>other_keywords</key>
		<dict>
			<key>match</key>
			<string>\b(as|delete|in|instanceof|is|native|new|to|typeof)\b</string>
			<key>name</key>
			<string>keyword.other.actionscript.3</string>
		</dict>
		<key>other_operators</key>
		<dict>
			<key>match</key>
			<string>(\.|=)</string>
			<key>name</key>
			<string>keyword.operator.actionscript.3</string>
		</dict>
		<key>package</key>
		<dict>
			<key>begin</key>
			<string>(^|\s+)(package)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.package.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#package_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#return_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#use_namespace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interface</string>
				</dict>
			</array>
		</dict>
		<key>package_name</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=package)\s+([\w\._]*)\b</string>
			<key>end</key>
			<string>\{</string>
			<key>name</key>
			<string>meta.package_name.actionscript.3</string>
		</dict>
		<key>primitive_types</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.actionscript.3</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(int|uint|Number|Boolean|String|\*(?&lt;=a))\b</string>
		</dict>
		<key>regexp</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[=(:]|^|return)\s*(/)(?![/*+{}?])</string>
			<key>end</key>
			<string>[^\\](/)[igsmx]*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>constant.character.escape.actionscript.3</string>
				</dict>
			</array>
		</dict>
		<key>return_type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.actionscript.3</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.type.actionscript.3</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\:)\s*(([\.\w]+)(\.&lt;([\.\w]+)&gt;)?|\*)</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>metadata</key>
		<dict>
			<key>begin</key>
			<string>\[\s*\b(\w+)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.metadata_info.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#metadata_info</string>
				</dict>
			</array>
		</dict>
		<key>use_namespace</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) (^|\s+|;) (use\s+)? (namespace) \s+ (\w+) \s* (;|$)</string>
		</dict>
		<key>variable_declaration</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.actionscript.3</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) ((static)\s+)? ((\w+)\s+)? ((static)\s+)? (const|var) \s+</string>
			<key>name</key>
			<string>meta.variable_declaration.actionscript.3</string>
		</dict>
		<key>vector_creation_operators</key>
		<dict>
			<key>match</key>
			<string>(&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.actionscript.3</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.actionscript.3</string>
	<key>uuid</key>
	<string>aa6f75ba-ab10-466e-8c6f-28c69aca1e9d</string>
</dict>
</plist>