<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mxml</string>
	</array>
	<key>name</key>
	<string>MXML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?=&lt;(?:fx|mx):Script(?:\s+(?:\w+:)?\w+=(["']).+\1)*\s*&gt;)</string>
			<key>end</key>
			<string>(?&lt;=&lt;\/(?:fx|mx):Script&gt;)</string>
			<key>name</key>
			<string>meta.script.mxml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;(?:fx|mx):Script[^&gt;]*&gt;</string>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;\/(?:fx|mx):Script&gt;</string>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=&lt;!\[CDATA\[)</string>
					<key>end</key>
					<string>(?&lt;=\]\]&gt;)</string>
					<key>name</key>
					<string>meta.cdata.mxml.script</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.actionscript.3</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;(?:fx|mx):Style&gt;</string>
			<key>end</key>
			<string>&lt;\/(?:fx|mx):Style&gt;</string>
			<key>name</key>
			<string>entity.name.tag.xml.mxml.style</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=&lt;(?:fx|mx):Metadata(?:\s+(?:\w+:)?\w+=(["']).+\1)*\s*&gt;)</string>
			<key>end</key>
			<string>(?&lt;=&lt;\/(?:fx|mx):Metadata&gt;)</string>
			<key>name</key>
			<string>meta.metadata.mxml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;(?:fx|mx):Metadata[^&gt;]*&gt;</string>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;\/(?:fx|mx):Metadata&gt;</string>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*\*(?!/)</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.actionscript.3</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>@(copy|default|eventType|example|exampleText|includeExample|inheritDoc|internal|param|private|return|see|since|throws)\b</string>
							<key>name</key>
							<string>keyword.other.documentation.actionscript.3.asdoc</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>metadata</key>
		<dict>
			<key>begin</key>
			<string>\[\s*\b(\w+)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.actionscript.3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.metadata_info.actionscript.3</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#metadata_info</string>
				</dict>
			</array>
		</dict>
		<key>metadata_info</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.actionscript.3</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)\s*=</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.actionscript.3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.actionscript.3</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.mxml</string>
</dict>
</plist>
